"""Cypher Sanitizer — Chặn destructive queries (DELETE/DROP/SET/MERGE).

Defense-in-depth layer: blocks any Cypher query containing write/delete operations
before it reaches Neo4j. In the current architecture (Phương án C), Cypher is
generated by templates so this is a safety net, not the primary defense.
"""

import re
import logging
from ai_engine.utils.cypher_validator import DESTRUCTIVE_KEYWORDS

logger = logging.getLogger(__name__)


def sanitize_cypher(cypher: str) -> str:
    """Sanitize a Cypher query by blocking destructive commands.

    This function acts as a safety net. If the query contains any
    write/delete/modify operations, a ValueError is raised instead
    of allowing it to reach Neo4j.

    Args:
        cypher: The Cypher query string to sanitize.

    Returns:
        The original query string if it is safe (read-only).

    Raises:
        ValueError: If destructive patterns are detected in the query.
    """
    if not cypher or not cypher.strip():
        raise ValueError("Cypher query is empty.")

    for pattern in DESTRUCTIVE_KEYWORDS:
        match = re.search(pattern, cypher, re.IGNORECASE)
        if match:
            name = match.group()
            logger.error(
                "Cypher sanitizer BLOCKED destructive command '%s' in: %s",
                name,
                cypher[:200],
            )
            raise ValueError(
                f"Destructive Cypher command '{name}' is not allowed. "
                f"Only read operations (MATCH/RETURN/WHERE/WITH) are permitted."
            )

    return cypher
